# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Run tests in default
      run: |
        cd default
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements-dev.txt
        pytest
        deactivate
    - name: Run tests in webhook
      run: |
        cd webhook
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements-dev.txt
        pytest
        deactivate
    - name: Run tests in capstone/files
      run: |
        cd capstone/files/app
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements-dev.txt
        pytest
        deactivate
    - name: Run tests in capstone/feed-fetching
      run: |
        cd capstone/feed-fetching
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements-dev.txt
        pytest
        deactivate

